targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
unmaintained = "deny"
ignore = []

[bans]
multiple-versions = "deny"
skip = [
    # most crates still reference the pre 1.0 version
    { name = "cfg-if", version = "=0.1.10" },
]
skip-tree = [
    # hyper (via h2) uses an outdated version
    { name = "pin-project", version = "=0.4.27" },
]

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = ["Apache-2.0", "MIT", "Unicode-DFS-2016"]
exceptions = [
    { allow = [
        "ISC",
    ], name = "untrusted" },
    { allow = [
        "ISC",
        "MIT",
        "OpenSSL",
    ], name = "ring" },
    { allow = [
        "Zlib",
    ], name = "tinyvec" },
]

[[licenses.clarify]]
name = "encoding_rs"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [{ path = "COPYRIGHT", hash = 0x39f8ad31 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[[licenses.clarify]]
name = "rustls-webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]
